server:
  port: 9000

spring:
  application:
    name: FinanceLoanApp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Finapp
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ankitdg7588@gmail.com
    password: wmbw gltj ifye soxn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            
  main:
    allow-bean-definition-overriding: true
            

logging:
  level:
    org.springframework.security: INFO
